clearml-iri-launch \
  --project-name "AmSC/pipeline-iri-bridge" \
  --task-name "submit-iri-job" \
  --repo https://github.com/zhenghh04/alcf_clearml_deployment.git \
  --branch main \
  --working-directory . \
  --facility alcf \
  --system polaris \
  --job-payload-file /tmp/iri_payload.json \
  --queue crux-services \
  --tags-json '["iri-bridge"]'
